name: '$(date:yyyy).$(date:MM).$(date:dd)$(Rev:.rr)'

trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: utilities
      type: git
      name: Az.Templates.Demo.DevOps
      ref: refs/heads/master
jobs:
  - template: eng/pipelines/templates/run-tests-job-template.yml@utilities
    parameters:
      project: 
        name: Demo.API
        publishTestBuildAsArtifact: false
        publishCodeCoverage: true
        continueOnTestRunError: false
        tests:
        - projects: '**/*.UnitTest.csproj'
          workingDirectory: $(System.DefaultWorkingDirectory)/test

  - job: pipelineJob
    steps:
      - script: echo This job runs after the template job